knp_paginator:
    page_range: 5                       # Nombre de pages affichées
    default_options:
        page_name: page                 # Nom du paramètre de page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'  # Template Bootstrap 5
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'