# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profiles'
    team_logos_directory: '%kernel.project_dir%/public/uploads/teams'
    cv_directory: '%kernel.project_dir%/public/uploads/cv'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CloudinaryUploader:
        arguments:
            $cloudName: '%env(CLOUDINARY_CLOUD_NAME)%'
            $apiKey: '%env(CLOUDINARY_API_KEY)%'
            $apiSecret: '%env(CLOUDINARY_API_SECRET)%'
            $defaultFolder: '%env(default::CLOUDINARY_DEFAULT_FOLDER)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Configuration du service d'email pour les applications coach
    App\Service\CoachApplicationEmailService:
        arguments:
            $fromEmail: '%env(MAILER_FROM_EMAIL)%'
            $fromName: '%env(MAILER_FROM_NAME)%'